name: pytorch_daikuai
channels:
  - pytorch
  - conda-forge
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - absl-py=1.4.0=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.0=h5eee18b_0
  - ca-certificates=2021.10.8=ha878542_0
  - certifi=2021.10.8=py37h89c1867_2
  - colorama=0.4.5=pyhd8ed1ab_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - dataclasses=0.8=pyhc8e2a94_3
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h0708190_1
  - fvcore=0.1.5.post20220512=pyhd8ed1ab_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - grpcio=1.42.0=py37hce63b2e_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - iopath=0.1.9=pyhd8ed1ab_0
  - jpeg=9d=h7f8727e_0
  - lame=3.100=h7f98852_1001
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libedit=3.1.20210910=h7f8727e_0
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h516909a_0
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.15.8=h780b84a_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.0.10=hc3755c2_1005
  - libuv=1.40.0=h7b6447c_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - markdown=3.4.3=pyhd8ed1ab_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h5e8e339_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h219a48f_0
  - ncurses=6.3=h7f8727e_2
  - nettle=3.6=he412f7d_0
  - numpy=1.21.5=py37he7a7128_1
  - numpy-base=1.21.5=py37hf524024_1
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openssl=1.1.1l=h7f98852_0
  - pip=21.2.2=py37h06a4308_0
  - portalocker=2.5.1=py37h89c1867_0
  - protobuf=3.15.8=py37hcd2ae1e_0
  - python=3.7.6=h0371630_2
  - python_abi=3.7=2_cp37m
  - pytorch=1.10.1=py3.7_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pyyaml=5.4.1=py37h5e8e339_0
  - readline=7.0=h7b6447c_5
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.33.0=h62c20be_0
  - tabulate=0.8.10=pyhd8ed1ab_0
  - tensorboard=1.15.0=py37_0
  - termcolor=2.0.1=pyhd8ed1ab_1
  - tk=8.6.11=h1ccaba5_0
  - torchaudio=0.10.1=py37_cu113
  - torchvision=0.11.2=py37_cu113
  - typing_extensions=4.2.0=pyha770c72_1
  - werkzeug=2.1.2=pyhd8ed1ab_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yacs=0.1.8=pyhd8ed1ab_0
  - yaml=0.2.5=h516909a_0
  - zipp=3.11.0=py37h06a4308_0
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.4.9=ha95c52a_0
  - pip:
      - appdirs==1.4.4
      - attrs==23.2.0
      - av==10.0.0
      - backcall==0.2.0
      - charset-normalizer==2.1.1
      - click==8.1.3
      - cycler==0.11.0
      - decorator==4.4.2
      - docker-pycreds==0.4.0
      - einops==0.6.0
      - filelock==3.9.0
      - fonttools==4.33.3
      - gitdb==4.0.10
      - gitpython==3.1.31
      - h5py==3.7.0
      - hickle==5.0.2
      - huggingface-hub==0.11.1
      - idna==3.4
      - imageio==2.18.0
      - imageio-ffmpeg==0.4.9
      - importlib-metadata==6.0.0
      - importlib-resources==5.12.0
      - ipdb==0.13.13
      - ipython==7.34.0
      - jedi==0.18.2
      - joblib==1.3.2
      - jsmin==3.0.1
      - jsonschema==4.17.3
      - kiwisolver==1.4.2
      - kornia==0.6.12
      - lpips==0.1.4
      - matplotlib==3.5.1
      - matplotlib-inline==0.1.6
      - moviepy==1.0.3
      - networkx==2.6.3
      - opencv-python==4.5.5.64
      - packaging==21.3
      - pandas==1.3.5
      - parso==0.8.3
      - pathtools==0.1.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.1.0
      - pkgutil-resolve-name==1.3.10
      - proglog==0.1.10
      - prompt-toolkit==3.0.38
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pygments==2.15.1
      - pyparsing==3.0.8
      - pyrsistent==0.19.3
      - pysteps==1.8.0
      - python-dateutil==2.8.2
      - pytorch-msssim==1.0.0
      - pytz==2023.3
      - pywavelets==1.3.0
      - requests==2.28.1
      - scikit-image==0.18.1
      - scipy==1.7.3
      - sentry-sdk==1.25.1
      - setproctitle==1.3.2
      - setuptools==58.0.4
      - smmap==5.0.0
      - tensorboard-logger==0.1.0
      - tifffile==2021.11.2
      - timm==0.6.12
      - tomli==2.0.1
      - tqdm==4.64.0
      - traitlets==5.9.0
      - urllib3==1.26.13
      - wandb==0.15.4
      - wcwidth==0.2.6
prefix: /home/ices/miniconda3/envs/pytorch_daikuai
